name: The Stampede
favicon: null
layout_spectrum: 0.11339415609836578
typography_spectrum: 0.6466368022374809
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.620529095409438
  lightness: 0.04379576584324241
  saturation: 0.7535532189067453
  rhythmicContrast: 0.3389472065027803
purpose: []
